### ISSUE TITLE
Client-side support?

### ISSUE THREAD

**Issue by matthewgertner** [jmdobry/disqus-node#15]
I'd like to use your package for a client-side web app using Browserify. The problem is that you currently require the `api_secret` for all APIs, which precludes use on the client side unless you want to expose your key to the world. Some APIs (e.g. `details`) will work with the public key, and I guess that client-side OAuth can be performed without the secret key, right? Would it make sense to add support for this to your package?

**Comment by jmdobry** [comment]
`disqus-node` was made specifically for NodeJS. The CLI code would be dead weight in the browser, and I think the size of the browserified file would be unreasonable. I think it makes more sense for a client-side disqus client to be its own library, with its own made-for-the-browser dependencies.

**Comment by matthewgertner** [comment]
Fair enough.
